### ISSUE TITLE
Add userid parameter to drush commands

### ISSUE THREAD

**Issue by mjordan** [dannylamb/migrate_islandora_csv#4]
https://github.com/Islandora-CLAW/islandora/pull/108 added `--userid=1` to `drush mim`. Examples in this tutorial should include that. I'll open a PR.

**Comment by dannylamb** [comment]
Resolved with https://github.com/dannylamb/migrate_islandora_csv/commit/a25f6c4e1b5bebdb7615da1a5fc8a96f2136fc98
