### ISSUE TITLE
The "migration" plugin does not exist - MigratePluginManager

### ISSUE THREAD

**Issue by red7-soporte** [dannylamb/migrate_islandora_csv#44]
Hello!

We are trying to import data to 'Paragraph fields' using migrate_islandora_csv onIslandora 2 (Docker containers), and Drupal 9.
the import process of  node yml, doesn't work.

The paragrahs yml works fine (paragrap_identifiers), 

![imagen](https://user-images.githubusercontent.com/60528355/155394570-cce817f4-6479-440f-b1c0-7286ae060321.png)

We are looking for the plugin in Drupal site: MigratePluginManager, but we don't see for drupal 9 compatibility 

![imagen](https://user-images.githubusercontent.com/60528355/155395259-f62bed4c-32ee-4a97-b03f-a7609de62ffc.png)

Any advice?

Thanks .

**Comment by jordandukart** [comment]
As discussed in Slack https://islandora.slack.com/archives/CM5PPAV28/p1647452654192039 (and identified by @seth-shaw-unlv ), issue appears to be with migration configuration that does not ship with this module. Going to go ahead and close this.
